# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171102_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'verbose_name': 'Contact Address', 'verbose_name_plural': 'Contact Addresses'},
        ),
        migrations.AlterModelOptions(
            name='studentaddress',
            options={'verbose_name': 'Student Address', 'verbose_name_plural': 'Student Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentphone',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
