# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171102_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContactLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentcontact_contact', to='student.Contact')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentcontact_student', to='student.Student')),
            ],
        ),
    ]
