# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentcontactlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcontactlink',
            options={'verbose_name': 'Student Contact', 'verbose_name_plural': 'Student Contacts'},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'student'),
        ),
    ]
